# Generated by Django 5.0 on 2024-01-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('content', models.TextField(max_length=250)),
                ('author', models.TextField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
