# Generated by Django 5.0 on 2024-01-13 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
    ]
